dirs:
  - .
useGitIgnore: true
excludedDirs:
  - node_modules

# Currently not crawling links matching the following pattern due to HTTP 429 errors
# See https://github.com/brimdata/super/pull/5887
ignorePatterns:
  - pattern: '^https://github.com/brimdata/super/blob/main/scripts/super-cmd-perf.*$'
  - pattern: '^https://dl.acm.org/doi/pdf/10.1145/984549.984551$'
